@startuml casosdeuso
left to right direction

"Professor Ecomp" as Prof
"Aluno Ecomp" as Aluno
"Visitante" as Visit

package Sistema_de_Gestão_de_TCC {
"Visualizar TCCs" as (Visualizar)
"Buscar TCCs" as (Buscar)
"Filtrar Busca de TCCs" as (Filtrar)
"Fazer Download da Monografia" as (Download)
"Fazer Login" as (Login)
"Editar Paginação da Lista de TCCs" as (Paginar)
"Recuperar Senha" as (Senha)
"Fazer Cadastro" as (Cadastro)
"Marcar Data de Defesa" as (Data)
"Admnistrar a Aplicação" as (Adm)
}
:Prof: -up-> (Buscar)
:Prof: -up-> (Visualizar)
:Prof: -up-> (Download)
:Prof: -up-> (Filtrar)
:Prof: -up-> (Paginar)
:Prof: -up-> (Login)
:Prof: -up-> (Senha)
:Prof: -up-> (Data)
:Prof: -up-> (Adm)

:Visit: --> (Visualizar)
:Aluno: --> (Visualizar)


:Visit: --> (Buscar)
:Aluno: --> (Buscar)

:Visit: --> (Download)
:Aluno: --> (Download)

:Visit: --> (Filtrar)
:Aluno: --> (Filtrar)

:Visit: --> (Paginar)
:Aluno: --> (Paginar)

:Visit: --> (Cadastro)

:Aluno: --> (Login)
:Aluno: --> (Senha)

:Aluno: --> (Data)

:Visit: --> (Cadastro)
@enduml