@startuml casosdeuso
left to right direction

"Banca" as Banca
"Aluno Ecomp" as Aluno
"Visitante" as Visit

"Orientador" as Orie
"Co-Orientador" as Coor
"Avaliador" as Aval

:Banca: <|-- Orie
:Banca: <|-- Coor
:Banca: <|-- Aval

package Monitora_TCC {
"Visualizar TCC" as (Visualizar)
"Listar TCCs" as (Listar)
"Buscar TCCs" as (Buscar)
"Fazer Download da Monografia" as (Download)
"Fazer Login" as (Login)
"Editar Paginação" as (Paginar)
"Recuperar Senha" as (Senha)
"Fazer Cadastro" as (Cadastro)
"Marcar Data de Defesa" as (Data)
"Fazer Upload de Monografia" as (Upload)
"Gerar Ata de Bancas" as (Atas)
"Gerenciar Cronograma da Banca" as (Crono)
"Aprovar Monografia" as (Aprovar)
}

:Banca: -up-> (Listar)
:Banca: -up-> (Visualizar)
:Banca: -up-> (Download)
:Banca: -up-> (Buscar)
:Banca: -up-> (Paginar)
:Banca: -up-> (Login)
:Banca: -up-> (Senha)
:Coor: -up-> (Upload)
:Orie: -up-> (Upload)

:Orie: -up-> (Atas)


:Visit: --> (Visualizar)
:Aluno: --> (Visualizar)

:Visit: --> (Listar)
:Aluno: --> (Listar)

:Visit: --> (Download)
:Aluno: --> (Download)

:Visit: --> (Buscar)
:Aluno: --> (Buscar)

:Visit: --> (Paginar)
:Aluno: --> (Paginar)

:Visit: --> (Cadastro)

:Aluno: --> (Login)
:Aluno: --> (Senha)

:Aluno: --> (Data)
(Data) --> :Banca:

:Orie: -up-> (Crono)

:Aval: -up-> (Aprovar)
:Orie: -up-> (Aprovar)
@enduml