@startuml casosdeuso
left to right direction

"Aluno eComp" as Aluno
"Visitante" as Visit

"Sistema TCC" as Sist
"Orientador" as Prof


package Monitora_TCC {
"Gerar declaração de participação de banca" as (participacao)
"Listar TCCs" as (Listar)
"Buscar TCCs" as (Buscar)
"Fazer Download de TCC" as (Download)
"Fazer Login" as (Login)
"Marcar Data de Defesa" as (Data)
"Fazer Upload de Monografia" as (Upload)
"Gerar Ata de Bancas" as (Atas)
"Gerar Cronograma de Defesas" as (Crono)
"Gerar Termo de Compromisso de Orientação" as (Compromisso)
}

:Prof: --> (Buscar)
:Prof: --> (participacao)
:Prof: --> (Download)
:Prof: --> (Listar)
:Prof: --> (Upload)
:Prof: --> (Login)

:Aluno: --> (Listar)
:Aluno: --> (Download)
:Aluno: --> (Buscar)
:Aluno: --> (Login)
:Aluno: --> (Data)
:Aluno: --> (Compromisso)

(Participacao) -- :Sist:
(Upload) --> :Sist:

:Visit: --> (Listar)
(Listar) --> :Sist:

:Visit: --> (Download)
(Download) --> :Sist:

:Visit: --> (Buscar)


(Data) --> :Prof:

(Compromisso) -- :Sist:

:Sist: -up-> (Atas)
:Sist: -up-> (Crono)
@enduml