@startuml casosdeuso
left to right direction

"Aluno eComp" as Aluno
"Visitante" as Visit

"Sistema TCC" as Sist
"Orientador" as Prof


package Monitora_TCC {
"Visualizar TCC" as (Visualizar)
"Listar TCCs" as (Listar)
"Buscar TCCs" as (Buscar)
"Fazer Download de TCC" as (Download)
"Fazer Login" as (Login)
"Marcar Data de Defesa" as (Data)
"Fazer Upload de Monografia" as (Upload)
"Gerar Ata de Bancas" as (Atas)
"Gerar Cronograma de Defesas" as (Crono)
"Gerar Termo de Concordância de Orientação" as (Termo)
}

:Prof: -up-> (Buscar)
:Prof: -up-> (Visualizar)
:Prof: -up-> (Download)

:Prof: -up-> (Listar)

:Prof: -up-> (Upload)
(Upload) --> :Sist:

:Visit: --> (Visualizar)
:Aluno: --> (Visualizar)

:Visit: --> (Listar)
:Aluno: --> (Listar)
(Listar) --> :Sist:

:Visit: --> (Download)
:Aluno: --> (Download)
(Download) --> :Sist:

:Visit: --> (Buscar)
:Aluno: --> (Buscar)

:Aluno: --> (Login)
:Prof: -up-> (Login)

:Aluno: --> (Data)
(Data) --> :Prof:

:Aluno: --> (Termo)
(Termo) --> :Sist:

:Sist: -up-> (Atas)
:Sist: -up-> (Crono)
@enduml