@startuml casosdeuso
left to right direction

"Aluno eComp" as Aluno
"Orientador" as Prof
"Visitante" as Visit

"Sistema TCC" as Sist


package Monitora_TCC {
"Gerar declaração de participação de banca" as (Participacao)
"Listar TCCs" as (Listar)
"Buscar TCCs" as (Buscar)
"Fazer Download de TCC" as (Download)
"Fazer Login" as (Login)
"Marcar Data de Defesa" as (Data)
"Fazer Upload de Monografia" as (Upload)
"Gerar Ata de Bancas" as (Atas)
"Defesas Agendadas" as (Agendar)
"Gerar Termo de Compromisso de Orientação" as (Compromisso)
}

:Prof: ---> (Listar)
:Prof: ---> (Download)
:Prof: ---> (Buscar)
:Prof: ---> (Participacao)
:Prof: ---> (Upload)
:Prof: ---> (Atas)
:Prof: ---> (Data)
:Prof: ---> (Login)
:Prof: ---> (Agendar)

:Aluno: --> (Listar)
:Aluno: --> (Download)
:Aluno: --> (Agendar)
:Aluno: --> (Buscar)
:Aluno: --> (Login)
:Aluno: --> (Compromisso)

:Visit: --> (Listar)
:Visit: --> (Download)
:Visit: --> (Agendar)
:Visit: --> (Buscar)

(Participacao) -- :Sist:
(Upload) -- :Sist:
(Listar) -- :Sist:
(Download) -- :Sist:
(Compromisso) -- :Sist:
(Agendar) -- :Sist:
(Atas) -- :Sist:
(Data) -- :Sist:

@enduml